### ISSUE TITLE
Ambiguity with JavaFX 19 Flat Map method and others

### ISSUE THREAD

**Issue by Siedlerchr** [tobiasdiez/EasyBind#67] opened 2022-08-16 19:28 UTC
I was testing JavaFX 19 ea in JabRef and get compile errors due to ambiguity:

`The method flatMap(Function<String,Optional<SpecialFieldValueViewModel>>) is ambiguous for the type OptionalBinding<String>`

JavaFX19  introduced new fluent binding methods for map and flat map and orElse. Would be great to have compatibility for them asap:
I think the OptionalBinding is obsolete now

https://github.com/openjdk/jfx/commit/60c75b82a4e1523b108fa79f44084190d78f5be1

**Comment by tobiasdiez** [comment] 2022-08-16 20:48
At least on a first glance, these newly introduced methods still don't allow the destinction between null and empty optional.

Any idea how to make it possible to use easybind with the new JFX version?

Closing as duplicate of #63.

**Closed by tobiasdiez** 2022-08-16 20:48 UTC
